apiVersion: v1
kind: ConfigMap
metadata:
  name: fgw-config
  namespace: filecoin-gateway
data:
  settings.env: |
    RIBS_YUGABYTE_SQL_HOST=yugabyte.filecoin-gateway.svc.cluster.local
    RIBS_YUGABYTE_SQL_PORT=5433
    RIBS_YUGABYTE_SQL_DB=filecoingw
    RIBS_YUGABYTE_CQL_HOSTS=yugabyte.filecoin-gateway.svc.cluster.local
    RIBS_YUGABYTE_CQL_PORT=9042
    RIBS_YUGABYTE_CQL_KEYSPACE=filecoingw
    RIBS_S3API_BIND_ADDR=:8078
    RIBS_S3API_REGION=EU
    EXTERNAL_LOCALWEB_BUILTIN_SERVER=true
    EXTERNAL_LOCALWEB_SERVER_PORT=443
    EXTERNAL_LOCALWEB_SERVER_TLS=true
    EXTERNAL_LOCALWEB_PATH=/root/.ribsdata/cardata
    EXTERNAL_LOCALWEB_URL=https://fgw.example.com
    RIBS_PROMETHEUS_PORT=2112
    # deal-making: adjust to taste
    RIBS_MINIMUM_REPLICA_COUNT=5
    RIBS_MAXIMUM_REPLICA_COUNT=10
    RIBS_MINIMUM_RETRIEVABLE_COUNT=3
    RIBS_RETRIEVABLE_REPAIR_THRESHOLD=2
    RIBS_RUN_SP_CRAWLER=true
    RIBS_ENABLE_PARALLEL_WRITES=false
    # F10: if CIDGravity free-tier GBAP returns non-200, uncomment
    # these to use fallback providers directly:
    # RIBS_DEAL_FALLBACK_PROVIDERS=f02620,f01249
    # RIBS_DEAL_FALLBACK_PROVIDERS_ONLY=true
